title: Hello! I'm Lucas Barros
description: > # this means to ignore newlines until "baseurl:. Put here a description for google results purpose"
  Lucas Barros's personal blog for software development, data science and telecomunications. 
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://lucasbarros.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lucas Barros # add your name
author-img: lucas-avatar.png # add your photo
about-author: I am a telecommunications engineer, focusing on software development and data science. A technology enthusiast. # add description
social-github: lucasuf # add your Github handle
social-linkedin: barroslucas # add your Linkedin handle
social-email: lucasbarros689@gmail.com # add your Email address

# Disqus
discus-identifier: lucasbarros-dev # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
